// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB37Il03Dy-eI5gEn_HS0Ouj_X6cNCDflE',
    appId: '1:856091302296:web:250b520b3502fb32f1b3ed',
    messagingSenderId: '856091302296',
    projectId: 'edutrack-91158',
    authDomain: 'edutrack-91158.firebaseapp.com',
    storageBucket: 'edutrack-91158.firebasestorage.app',
    measurementId: 'G-V1C384ZS7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe_iYeHVixaYR5GczPNVJ9M3jXOoYp_dQ',
    appId: '1:856091302296:android:6879933470364ecbf1b3ed',
    messagingSenderId: '856091302296',
    projectId: 'edutrack-91158',
    storageBucket: 'edutrack-91158.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYI30CnXdqInxOGKiXNl2kFIN6ax8gxdY',
    appId: '1:856091302296:ios:e563a89ea0711c37f1b3ed',
    messagingSenderId: '856091302296',
    projectId: 'edutrack-91158',
    storageBucket: 'edutrack-91158.firebasestorage.app',
    iosBundleId: 'com.example.eduTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYI30CnXdqInxOGKiXNl2kFIN6ax8gxdY',
    appId: '1:856091302296:ios:e563a89ea0711c37f1b3ed',
    messagingSenderId: '856091302296',
    projectId: 'edutrack-91158',
    storageBucket: 'edutrack-91158.firebasestorage.app',
    iosBundleId: 'com.example.eduTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB37Il03Dy-eI5gEn_HS0Ouj_X6cNCDflE',
    appId: '1:856091302296:web:adc575a570d8d5cef1b3ed',
    messagingSenderId: '856091302296',
    projectId: 'edutrack-91158',
    authDomain: 'edutrack-91158.firebaseapp.com',
    storageBucket: 'edutrack-91158.firebasestorage.app',
    measurementId: 'G-P7VPM7R3ZV',
  );
}
